import { StyleSheet } from "react-native";

export const paletteScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  container: {
    padding: 20,
    backgroundColor: "#f8f9fa",
    flexGrow: 1,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#333",
  },
  privacyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 8,
    marginVertical: 15,
    width: "60%",
    alignSelf: "center",
  },
  privacyButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  photo: {
    width: "100%",
    height: 250,
    borderRadius: 10,
    marginBottom: 20,
  },
  warningText: {
    textAlign: "center",
    color: "red",
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: "#fff",
    color: "#495057",
  },
  toggleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
  },
  toggleLabel: {
    fontSize: 16,
    color: "#333",
  },
  toggleButton: {
    marginLeft: 10,
  },
  toggleIndicator: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#adb5bd",
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "center", 
    gap: 10,
    marginTop: 15,
  },
  buttonShared: {
    flex: 1, 
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  
  buttonTextShared: {
    fontSize: 18,
    fontWeight: "600",
  },  
  saveButton: {
    backgroundColor: "#007bff",
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: "center",
    flex: 0.48,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  discardButton: {
    backgroundColor: "#dc3545",
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: "center",
    flex: 0.48,
  },
  discardButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  colorsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 10,
  },
  colorItem: {
    alignItems: "center",
    marginHorizontal: 10,
    marginBottom: 10,
  },
  colorSwatch: {
    width: 50,
    height: 50,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#ced4da",
  },
  colorHex: {
    marginTop: 5,
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  colorPickerContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    backgroundColor: "red",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  deleteButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  inputWrapper: {
    position: "relative",
    width: "100%",
    marginBottom: 15,
  },
  inputIconPencil: {
    position: "absolute",
    right: 10,
    top: "35%",
    transform: [{ translateY: -10 }],
  },
});
